customers/urls.py
from django.urls import path
from .views import render_pdf_view, CustomerListView, customer_render_pdf_view

app_name = 'customers'

urlpatterns = [
    path('', CustomerListView.as_view(), name='customer-List-view'),
    path('test/',render_pdf_view, name='test-view'),
    path('pdf/<pk>', customer_render_pdf_view, name='customer-pdf-view'),
    
    ]

pdf_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customers.urls', namespace='customers'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customers/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    partname = models.CharField(max_length=122)
    material = models.CharField(max_length=122)
    process = models.CharField(max_length=122)
    quantity = models.CharField(max_length=122)
    rate = models.CharField(max_length=122)
    total = models.CharField(max_length=122)
    date = models.DateTimeField()

    

customers/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from .models import Customer


# Create your views here.


def customer(request):
    # return HttpResponse("this is home page")
    if request.method == "POST":
        partname = request.POST.get('partname')
        material = request.POST.get('material')
        process = request.POST.get('process')
        quantity = request.POST.get('quantity')
        rate = request.POST.get('rate')
        total = request.POST.get('total')
        customer = Customer(partname=partname, material=material, process=process, quantity=quantity, rate=rate, total=total, date=datetime.today())
        customer.save()
        
    return render(request, ('main.html'))


class CustomerListView(ListView):
   model = Customer
   template_name = 'customers/main.html'

def customer_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    customer = get_object_or_404(Customer, pk=pk)
    template_path = 'customers/pdf2.html'
    context = {'customer': customer}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')

   #  if download:
   #  response['Content-Disposition'] = 'attachment; filename="report.pdf"'

   #if want to display in browser:
    response['Content-Disposition'] = 'filename="report.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response



def render_pdf_view(request):
    template_path = 'customers/pdf1.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')

   #  if download:
   #  response['Content-Disposition'] = 'attachment; filename="report.pdf"'

   #if want to display in browser:
    response['Content-Disposition'] = 'filename="report.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

customers/templates/customers/main.html
{% extends 'base.html' %}

{% block title %}
Customers
{% endblock %}

{% block body %}
<!-- {% for customer in object_list %} -->

<!-- {{customer}} -->

<div class="container my-3 mx-3">
    <form method="post" action="/main">
      {% csrf_token %}
      <div class="form-group">
        <label for="partname">Part Name</label>
        <input type="text" name="partname" class="form-control" id="partname" placeholder="">
      </div>
      <div class="form-group">
        <label for="material">Material</label>
        <input type="text" class="form-control" name="material" id="material" placeholder="">
      </div>
      <div class="form-group">
        <label for="process">Process</label>
        <input type="text" class="form-control" id="process" name="process" placeholder="">
      </div>
      <div class="form-group">
        <label for="quantity">Quantity</label>
        <select class="form-control" name="quantity" id="quantity">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
  
        <div class="form-group">
          <label for="rate">Rate</label>
          <input type="text" class="form-control" name="rate" id="rate" placeholder="">
        </div>
  
        <div class="form-group">
          <label for="total">Total</label>
          <input type="text" class="form-control" name="total" id="total" placeholder="">
        </div>
        <button class="btn btn-primary my-3" type="submit">Submit</button>
    </form>
    <br>
    <a href="{% url 'customers:customer-pdf-view' customer.pk %}"><buttom class="btn btn-primary">Print Pdf</buttom></a>
  </div>


<br>

<!-- {% endfor %} -->
{% endblock body %}

customers/templates/customers/pdf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{myvar}}
</body>
</html>

customers/templates/customers/pdf2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        html {
            font-family: 'Times New Roman', Times, serif;

        }

        .content span{
            font-weight: bold;
            font-size: 12px;
        }
        .content{
            font-size: 12px;
        }
    </style>
</head>

<body>

    <div class="header-content">
        <img src="https://cad-and-cart-bucket-v1.s3.ap-south-1.amazonaws.com/static/img/draft.png" width="300px" alt="">

        <div align="right" class="sales-info-box">
            <table style="width: 40%" align="right">
                <tr>
                    <td class="total-1" style="width:30%;">Hub Location: Pune</td>

                </tr>
                <tr>
                    <td class="total-1" style="width:30%;">Sales coordinator: Mahesh Takey</td>

                </tr>
                <tr>
                    <td class="total-1" style="width:30%;">Contact: +91-9637132001</td>

                </tr>
            </table>
        </div>
    </div>
    </div>

    <hr>
    <div class="content">

        <p><span>Partname: </span>{{customer.partname}}</p>
        <br>
        <p> <span>Material: </span> {{customer.material}}</p>
        <br>
        <p> <span>Process: </span> {{customer.process}}</p>
        <br>
        <p> <span>Qty: </span> {{customer.quantity}}</p>
        <br>
        <p> <span>Rate: </span> {{customer.rate}}</p>
        <hr>
        <p> <span>Total: </span> {{customer.total}}</p>
    </div>

    <hr>


    <div class="" style="margin-bottom: 0px!important;">
        <div class="company-1">Spire3d Technologies PVT LTD</div>
        <div class="company-2">Block F-2, MIDC
            <br>Pimpri Colony, Pimpri-Chinchwad
            <br>Pune, Maharashtra 41101
            <br>PAN ABDCS5705P
            <br>GSTIN 27ABDCS5705P1ZU
        </div>

    </div>

    <div class="notes">

        <p>Terms and Conditions:
            <br>Order Confirmation : Confirmation of order is done after Admin check.
            <br>Payment Terms : Minimum charges will be Rs 300/-
            <br>Payment Term : 50 % Advance payment before start of work.
            <br>Payments Term : 100 % payment before delivery.
            <br>Delivery Terms : Goods will be deliver after realization of Payment.
            <br>Delivery Condition : Courier charger will be extra.
            <br>Special Note : Collect your scrap within 1 week.
</body>

</html>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Features</a>
            <a class="nav-item nav-link" href="#">Pricing</a>
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
          </div>
        </div>
      </nav>

      {% block body %}  {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>